sudo: required
language: java
before_install:
    - chmod +x .travis/before_test.sh
    - chmod +x .travis/script.sh
    # java 6 require maven 3.2.5
    - wget http://mirrors.sonic.net/apache/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz
    - tar -zxf apache-maven-3.2.5-bin.tar.gz
    - sudo cp -R apache-maven-3.2.5 /usr/local
    - ls -lrt /usr/local/apache-maven-3.2.5/bin/
    - sudo ln -fs /usr/local/apache-maven-3.2.5/bin/mvn /usr/local/bin/mvn
    - mvn --version
    - echo "MAVEN_OPTS='-Xmx384m'" > ~/.mavenrc
install: .travis/before_test.sh
dist: trusty
jdk:
    - openjdk6
    - openjdk7
    - oraclejdk8
env:
    - AURORA=true
    - MARIA=5.5 PACKET=8M
    - MARIA=10.0 PACKET=8M
    - MARIA=10.1 PACKET=8M
    - MARIA=10.1 PACKET=20M
    - MARIA=10.1 PACKET=40M
    - MARIA=10.2 PACKET=8M
    - MARIA=10.2 PACKET=8M PROFILE=true
    - MARIA=10.2 PACKET=20M
    - MARIA=10.2 PACKET=40M
    - TYPE=PREPARE MARIA=10.1 PACKET=40M
    - TYPE=MAXSCALE MAXSCALE_VERSION=2.1.3 MARIA=10.1 PACKET=40M
    - TYPE=REWRITE MARIA=10.1 PACKET=40M
    - TYPE=MULTI MARIA=10.1 PACKET=40M
    - TYPE=BULK_SERVER MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_CLIENT MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_SERVER MARIA=10.1 PACKET=40M
    - COMPRESSION=false MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_SERVER MARIA=10.2 PACKET=40M
    - COMPRESSION=false MARIA=10.2 PACKET=40M
    - MYSQL=5.7 PACKET=8M
    - MYSQL=5.6 PACKET=8M
script: .travis/script.sh
