sudo: required
language: java
before_install:
    - chmod +x .travis/before_test.sh
    - chmod +x .travis/script.sh
install: .travis/before_test.sh
jdk:
    - oraclejdk8
    - oraclejdk7
env:
    - AURORA=true
    - MARIA=5.5 PACKET=8M
    - MARIA=5.5 PACKET=20M
    - MARIA=5.5 PACKET=40M
    - MARIA=10.0 PACKET=8M
    - MARIA=10.0 PACKET=20M
    - MARIA=10.0 PACKET=40M
    - MARIA=10.1 PACKET=8M
    - MARIA=10.1 PACKET=20M
    - MARIA=10.1 PACKET=40M
#    - MARIA=10.2 PACKET=8M //waiting for 10.2.2 release
#    - MARIA=10.2 PACKET=20M //waiting for 10.2.2 release
#    - MARIA=10.2 PACKET=40M //waiting for 10.2.2 release
    - TYPE=REWRITE MARIA=10.1 PACKET=40M
    - TYPE=MULTI MARIA=10.1 PACKET=40M
    - TYPE=BULK_CLIENT MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_CLIENT MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_SERVER MARIA=10.1 PACKET=40M
    - COMPRESSION=false MARIA=10.1 PACKET=40M
    - TYPE=NO_BULK_SERVER MARIA=10.2 PACKET=40M
    - COMPRESSION=false MARIA=10.2 PACKET=40M
    - MYSQL=5.7 PACKET=8M
    - MYSQL=5.7 PACKET=20M
    - MYSQL=5.7 PACKET=40M
    - MYSQL=5.6 PACKET=8M
    - MYSQL=5.6 PACKET=20M
    - MYSQL=5.6 PACKET=40M
script: .travis/script.sh
